# Generated by Django 4.0.1 on 2022-01-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('lni-cog', 'Gear'), ('lni-laptop-phone', 'Laptop'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers'), ('lni-rocket', 'Rocket')], max_length=18, verbose_name='Icon'),
        ),
    ]
